id: IF2957953
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T11:48:56+00:00'
last_modified: '2022-06-09T08:25:58.801777+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3MS866
  title: རྟགས་ཀྱི་འཇུག་པའི་དགོངས་འགྲེལ་རབ་གསལ་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E0A6:
      image_group_id: I3MS868
      title: Volume 1 of rtags kyi 'jug pa'i dgongs 'grel rab gsal snang ba/
      total_pages: 38
      order: 1
      base_file: E0A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
